sudo: required

services:
          - docker

env:
        global:
                - GIT_COMMIT=$TRAVIS_COMMIT
                - GIT_BRANCH=$TRAVIS_BRANCH
language: go

go:
        - 1.7.x

before_install:
        - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"

install:
          - echo $GIT_COMMIT $GIT_BRANCH;
script:
        - make build_artifacts
        - make build_docker
        - make docker_dockerhub_tag
        - make docker_dockerhub_push
