sudo: required

services:
          - docker

env:
        global:
                - GIT_COMMIT=$TRAVIS_COMMIT
language: go

go:
        - 1.7.x

before_install:
        - echo "branch:" $(TRAVIS_BRANCH) "tag:" $(TRAVIS_TAG)
        - docker login -u="$DOCKERHUB_USERNAME" -p="$DOCKERHUB_PASSWORD"
        - 'if [ -n "$($TRAVIS_TAG)" ]; then
               export GIT_BRANCH=$(TRAVIS_BRANCH);
          else
               export GIT_BRANCH=$(TRAVIS_TAG);
          fi'

install:
          - echo $GIT_COMMIT $GIT_BRANCH
script:
        - make build_artifacts
        - make build_docker
        - make docker_dockerhub_tag
        - make docker_dockerhub_push
