version: "{build}"

platform: x64

clone_folder: c:\gopath\src\github.com\tochka\test-travis

environment:
  GOPATH: c:\gopath

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

install:  
  - set PATH=%GOPATH%\bin;c:\go\bin;c:\MinGW\bin\;c:\MinGW\msys\1.0\bin;%PATH%
  - go version
  - mingw-get install msys-zip
  - mingw32-make.exe get
  
test_script:
  - mingw32-make.exe test_all
  
build_script:  
   - mingw32-make.exe
   - mingw32-make.exe build_artifact

artifacts:
  - path: build\windows-amd64.zip
