version: "{build}"

platform: x64

clone_folder: c:\gopath\src\github.com\tochka\test-travis

environment:
  GOPATH: c:\gopath

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

install:  
  - set PATH=%GOPATH%\bin;c:\go\bin;c:\MinGW\bin\;%PATH%
  - go version
  - copy c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - C:\MinGW\msys\1.0\msys.bat
  - C:\MinGW\msys\1.0\msys.bat install -y msys-zip
  - make get
  
test_script:
  - make test_all
  
build_script:  
   - make
   - make build_artifact

artifacts:
  - path: build\windows-amd64.zip
