version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\tochka\test-travis

environment:
  GOPATH: c:\gopath

skip_branch_with_pr: true

pull_requests:
  do_not_increment_build_number: true

install:  
  - set PATH=%GOPATH%\bin;c:\go\bin;c:\MinGW\bin\;c:\MinGW\msys\1.0\bin;%PATH%
  - go version
  - mingw32-make get

build_script:
   - mingw32-make
   - mingw32-make build_artifact

test_script:
  - dir
  - dir artf
  - mingw32-make test_all
  
artifacts:
  - path: artf\windows-amd64.zip
